name: Next.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Export application
        run: npm run export

      - name: Start Genkit server (and check flows load)
        run: |
          echo "Attempting to start Genkit server to check if flows load..."
          timeout 30s npm run genkit:dev
          EXIT_CODE=$?
          if [ $EXIT_CODE -eq 124 ]; then
            echo "Genkit server started successfully and was terminated by timeout (flows likely loaded)."
            exit 0 # Treat timeout as success for this check
          elif [ $EXIT_CODE -ne 0 ]; then
            echo "Genkit server failed to start (exit code $EXIT_CODE)."
            exit $EXIT_CODE # Propagate error
          else
            echo "Genkit server exited cleanly before timeout (unexpected, but assume success)."
            exit 0
          fi
